### PR TITLE
fix: gracefully handle missing objects for GCS checkpoints

### LINKED ISSUE #4451: GCS: validator fails to submit checkpoints
When running a validator with GCS for checkpoint syncer, it runs well for a minute or two until it gets stuck in a loop with an error:

```
  2024-09-07T11:00:41.564908Z  WARN hyperlane_core::rpc_clients::retry: Retrying call, retries: 2, error: EyreError(received unsuccessful response

Caused by:
   0: HTTP status
   1: 404 Not Found

Location:
    hyperlane-base/src/types/gcs_storage.rs:156:19)
    at hyperlane-core/src/rpc_clients/retry.rs:25
    in hyperlane_core::rpc_clients::retry::call_and_retry_n_times with n: 18446744073709551615

  2024-09-07T11:00:43.739198Z  WARN hyperlane_core::rpc_clients::retry: Retrying call, retries: 3, error: EyreError(received unsuccessful response

Caused by:
   0: HTTP status
   1: 404 Not Found

Location:
    hyperlane-base/src/types/gcs_storage.rs:156:19)
    at hyperlane-core/src/rpc_clients/retry.rs:25
    in hyperlane_core::rpc_clients::retry::call_and_retry_n_times with n: 18446744073709551615

  2024-09-07T11:00:45.924408Z  WARN hyperlane_core::rpc_clients::retry: Retrying call, retries: 4, error: EyreError(received unsuccessful response

Caused by:
   0: HTTP status
   1: 404 Not Found

Location:
    hyperlane-base/src/types/gcs_storage.rs:156:19)
    at hyperlane-core/src/rpc_clients/retry.rs:25
    in hyperlane_core::rpc_clients::retry::call_and_retry_n_times with n: 18446744073709551615

... etc
```

### PR DESCRIPTION
**Pull request by sapph1re**
### Description

The issue with the validator was that it wasn't handling the bucket's 404 response as a correct response when the object is not found when fetching a specific checkpoint or latest index, thus it was getting stuck in a loop failing to submit a checkpoint or get the latest stored index.

I fixed it by catching the 404 response in `gcs_storage.rs` and returning `Ok(None)` instead of raising an error, the same way it's handled in S3 Storage.

### Drive-by changes

Bumped ya-gcp to the latest 0.11.3

### Related issues

- Fixes #4451 

### Backward compatibility

Yes

### Testing

Manual

### CODE REVIEW

**Review by tkporter — APPROVED** [review]
Thank you 🫡

File: typescript/sdk/src/metadata/agentConfig.ts [hunk 1]
```diff
@@ -381,6 +381,27 @@ export const ValidatorAgentConfigSchema = AgentConfigSchema.extend({
           ),
       })
       .describe('A checkpoint syncer that uses S3'),
+    z
+      .object({
+        type: z.literal('gcs'),
```
Comment (jmrossy) [inline typescript/sdk/src/metadata/agentConfig.ts:386]: Can this utilize the value via the `CheckpointSyncerType` enum instead of duplicating the const here?

**Comment by sapph1re** [comment]
> please pull latest `main` after #4458 is merged to fix the `cli-advanced-e2e` test

done

File: typescript/sdk/src/metadata/agentConfig.ts (hunk 1 above)
Comment (sapph1re) [reply typescript/sdk/src/metadata/agentConfig.ts]: Resolving this to unblock the merging, if anyone still considers this substantial, let's create another issue about it like I suggested above.
