### PR TITLE
Fallback provider

### LINKED ISSUE #1538: Fallback provider
The quorum provider we currently use is expensive and also prone to issues if a majority of the providers go down. We would like to support an additional provider type which instead makes a single request and then "falls back" on the next one if there is a "retry-able" error (e.g. a 5xx error)

For now we just want a naive implementation that basically just always tries the first URL provided and if that fails try the next one and so on until it works or runs out of URLs.

This can lean heavily on the existing code for the quorum provider but we will need to make some changes to the config to support this pathway distinctly from quorum.

After deploying this for testing we should verify there are no common issues that require additional logic.

### PR DESCRIPTION
**Pull request by mattiecnvr**
### Description

New fallback provider

### Related issues

- Fixes #1538 

### Backward compatibility

_Are these changes backward compatible?_

Yes

_Are there any infrastructure implications, e.g. changes that would prohibit deploying older commits using this infra tooling?_

None

### Testing

_What kind of testing have these changes undergone?_

Manual - e2e test coverage has been extended to fallback provider

### CODE REVIEW

File: rust/chains/hyperlane-ethereum/src/fallback.rs [hunk 1]
```diff
@@ -0,0 +1,133 @@
...
+
+    /// Create a fallback provider.
+    pub fn build(self) -> FallbackProvider<T> {
+        FallbackProvider {
+            providers: self.providers,
+        }
+    }
+}
+
+/// Error thrown when sending an HTTP request
```
Comment (tkporter) [inline rust/chains/hyperlane-ethereum/src/fallback.rs:75]: nit: this comment feels inaccurate?

File: rust/chains/hyperlane-ethereum/src/trait_builder.rs [hunk 2]
```diff
@@ -104,6 +103,34 @@ pub trait BuildableWithProvider {
                 self.wrap_with_metrics(quorum_provider, locator, signer, middleware_metrics)
                     .await?
             }
+            ConnectionConf::HttpFallback { urls } => {
+                let rpc_metrics = rpc_metrics.map(|f| f());
+                let mut builder = FallbackProvider::builder();
+                let http_client = Client::builder()
+                    .timeout(HTTP_CLIENT_TIMEOUT)
```
Comment (tkporter) [inline rust/chains/hyperlane-ethereum/src/trait_builder.rs:110]: Just wanna flag that afaik we we haven't actually experienced many timeouts with our requests, but if for some reason the first provider has issues that result in the timeout consistently getting hit, we'll consistently take 1 min per request

Generally I don't think we should make any logic changes yet to deal with consistently failing primary providers, but I think we should set up alerts on the rate of this metric so that we can be aware if we're having a lot of failures:
```
hyperlane_request_failure_count{method!~"(eth_estimateGas|eth_sendRawTransaction|eth_sendTransaction)"}
```

File: rust/chains/hyperlane-ethereum/src/fallback.rs [hunk 3]
```diff
@@ -0,0 +1,133 @@
...
+use serde::{de::DeserializeOwned, Serialize};
+use serde_json::Value;
+use thiserror::Error;
+use tracing::warn;
+
+use ethers_prometheus::json_rpc_client::PrometheusJsonRpcClient;
+
+const METHODS_TO_NOT_TO_FALLBACK_ON: &[&str] = &[
+    "eth_estimateGas",
+    "eth_sendTransaction",
```
Comment (tkporter) [inline rust/chains/hyperlane-ethereum/src/fallback.rs:14]: I think `eth_sendTransaction` and `eth_sendRawTransaction` may actually be worth falling back on

The reasoning is that with QuorumProvider the race condition is pretty clear where if we send a tx to a bunch of providers, if provider A quickly propagates that tx to provider B before provider B processes our RPC, then provider B will complain even though the tx was submitted successfully to the general network via provider A.

Then thinking through the fallback provider case:
1. submit to provider A, it gives us an error
2. We should then try submitting to provider B. There's the chance that provider A somehow erroneously gave us an error in (1), in which case provider B may already know our tx and also give an error, but I think this is much less likely than a case where provider A gives an error because it's just broken

wdyt?

**Review by tkporter — APPROVED** [review]
Nice work! One suggestion on which RPCs to not retry, but also open to pushback. Excited to try this in rc

File: rust/chains/hyperlane-ethereum/src/fallback.rs (hunk 1 above)
Comment (mattiecnvr) [reply rust/chains/hyperlane-ethereum/src/fallback.rs:75]: Yeah, copy paste error, fixed.

File: rust/chains/hyperlane-ethereum/src/fallback.rs (hunk 3 above)
Comment (mattiecnvr) [reply rust/chains/hyperlane-ethereum/src/fallback.rs:14]: Well, this was actually the logic in retrying provider, not quorum provider. The reasoning was that if we got an error on this method it probably was a VM revert error and not a provider error.

Comment (tkporter) [reply rust/chains/hyperlane-ethereum/src/fallback.rs:14]: Lol https://github.com/hyperlane-xyz/hyperlane-monorepo/issues/706#issuecomment-1177476366

I think my motivation was probably to do with errors from eth_sendTransaction / eth_sendRawTransaction to do with nonces - e.g. if we submitted a tx accidentally with nonce `n - 1` when the latest nonce on chain is `n`, we will get an error and don't want to retry. Fwiw VM reverts in the transaction won't result in errors from th_sendTransaction / eth_sendRawTransaction

But yeah good point that we did have a reason to add this to the retrying provider. I'm happy to keep as is where we don't fall back

Comment (mattiecnvr) [reply rust/chains/hyperlane-ethereum/src/fallback.rs:14]: Okay, sg for now, might want to change in the future depending on what we observe.
