### PR TITLE
Quickstart fixes

### LINKED ISSUE #1163: Quickstart quick-fixes
- [ ] Make mock mailboxes conform to interfaces
- [x] Make mockinterchainaccountrouter and its interface
- [x] Modify interchainaccountrouters to return leafIndex
- [ ] Provide single call function signature
- [x] Expose Call on ICARouter
- [x] Export InterchainAccountRouter on core or sdk
- [x] Loosen type of ChainNameToDomainID
- [x] Loosen type of hyperlaneCoreAddresses

### PR DESCRIPTION
**Pull request by nambrot**
### Description

- Have InterchainAccountRouter and MockInterchainAccountRouter conform to IInterchainAccountRouter
- Have InterchainQueryRouter conform to IInterchainQueryRouter
- Made `ChainNameToDomainId` more forgiving type wise
- Loosen type of hyperlaneCoreAddresses

### Related issues

- Fixes #1163 

### Backward compatibility

_Are these changes backward compatible?_

No, new middleware routers will have to be deployed

_Are there any infrastructure implications, e.g. changes that would prohibit deploying older commits using this infra tooling?_

Yes, deploys from this commit won't yield the same bytecode and thus same contract addresses for middleware contracts

### Testing

_What kind of testing have these changes undergone?_

Unit Tests

### CODE REVIEW

File: typescript/sdk/src/types.ts [hunk 1]
```diff
@@ -6,6 +6,10 @@ import type { Chains } from './consts/chains';
 export type ChainName = keyof typeof Chains;
 // A full object map of all chains to a value type
 export type CompleteChainMap<Value> = Record<ChainName, Value>;
+export type ForgivingCompleteChainMap<Value> = Record<
```
Comment (jmrossy) [inline typescript/sdk/src/types.ts:9]: Is this a complete chain map?
How about `LooseChainMap` or `WeakChainMap`

**Review by jmrossy — APPROVED** [review]
