### PR TITLE
fix(cli): Update warp apply to apply changes in single command

### LINKED ISSUE #4671: fix: warp apply requires multiple calls for multiple updates
## Problem
Currently, `warp apply` only updates in place _or_ extends. It cannot do both in a single call. This is problematic because if there are both kinds of updates, then multiple `warp apply` are needed. 

As shown in Renzo's deployment config, a config is added to extend **and** a new multisig ISM is added for each existing chain. 

Update `warp apply` such that only 1 call is needed for all config updates.

### PR DESCRIPTION
**Pull request by ltyu**
### Description
This PR fixes a limitation in `warp apply` such that it can only extend _or_ update an existing warp route. This means that for configs with both changes require `warp apply` to be called multiple times. An example is when Renzo deploys to new chain, and it needs to update the existing ISMs.

### Related issues
- Fixes #4671 

### Backward compatibility
Yes

### Testing
Manual/Unit Tests

### CODE REVIEW

File: typescript/cli/src/deploy/warp.ts [hunk 1]
```diff
@@ -457,94 +448,119 @@ export async function runWarpRouteApply(
...
+    apiKeys,
+  );
 
-    await enrollRemoteRouters(params, mergedRouters);
+  const mergedRouters = mergeAllRouters(
+    multiProvider,
+    existingConfigs,
+    newDeployedContracts,
+    warpCoreConfigByChain,
+  );
```
Comment (yorhodes) [inline typescript/cli/src/deploy/warp.ts:514]: can we just join the newDeployedContracts with the existing deployed and pass that to the update step?

**Review by yorhodes — APPROVED** [review]
mostly lgtm although it would intuitively make more sense to me if we did
```
contracts = contracts.extend()
contracts.update()
```

**Review by xeno097 — APPROVED** [review]

File: typescript/cli/src/deploy/warp.ts (hunk 1 above)
Comment (ltyu) [reply typescript/cli/src/deploy/warp.ts:514]: i can try to do that in a next PR. wanted to keep the diffs to a minimal for this
