### PR TITLE
Proper RPC Useage fix

### LINKED ISSUE #1255: Proper fix for RPC usage issue
See https://github.com/hyperlane-xyz/hyperlane-monorepo/pull/1254 for initial solution.

### PR DESCRIPTION
**Pull request by mattiecnvr**
### Description

Two main things I wanted to do in this PR

1) End some of the duplication between the indexers
2) Implement a more robust RPC rate limiter

### Drive-by changes

No

### Related issues

- Fixes #1255 

### Backward compatibility

_Are these changes backward compatible?_

Yes

_Are there any infrastructure implications, e.g. changes that would prohibit deploying older commits using this infra tooling?_

None

### Testing

_What kind of testing have these changes undergone?_

Manual
Unit Tests

### CODE REVIEW

**Comment by mattiecnvr** [comment]
This is currently failing the unit tests but it is passing the E2E tests. I wanted to at least get this in front of you now so you could give some early feedback.

In addition to logic validation, I would like to request suggestions on a better name than `ContractSyncHelper`.

**Review by tkporter — APPROVED** [review]
lgtm - a couple non-blocking suggestions / questions

File: rust/abacus-base/src/contract_sync/mod.rs [hunk 1]
```diff
@@ -47,3 +53,104 @@ impl<I> ContractSync<I> {
...
+            match self.indexer.get_finalized_block_number().await {
+                Ok(tip) => {
+                    // we retrieved a new tip value, go ahead and update.
+                    self.last_tip_update = Instant::now();
+                    self.tip = tip;
+                    Ok(())
+                }
+                Err(e) => {
+                    // we are failing to make a basic query, we should wait before retrying.
+                    sleep(Duration::from_secs(10)).await;
```
[the remark this answers is not in the document]
Comment (mattiecnvr) [reply rust/abacus-base/src/contract_sync/mod.rs:150]: Benefit is backing off on the RPC provider if they are giving us errors for what should be a trivial request. The cause of such an error could be a few different things, but best practice is to not rapidly spam the same query if it is returning an error to give a chance for them to recover and avoid a retry-storm. Since this is a query that, in theory, should never fail, it seems reasonable to assume that an error here is indicating an issue on their end (or rate limiting).

File: rust/abacus-base/src/contract_sync/interchain_gas.rs [hunk 2]
```diff
@@ -83,7 +73,6 @@ where
                 stored_messages.inc_by(new_payments_processed);
 
                 db.store_latest_indexed_gas_payment_block(to)?;
```
[the remark this answers is not in the document]
Comment (mattiecnvr) [reply rust/abacus-base/src/contract_sync/interchain_gas.rs:75]: Ah, yeah, okay, this is an easy enough fix. My gut reaction though here is to use start_block and not `from` since it is the "full chunk from" and that could technically lead to us backtracking. I think we might also want to change that in the outbox to not use full chunk from but rather the `start_block`. Thoughts?

File: rust/abacus-base/src/contract_sync/mod.rs [hunk 3]
```diff
@@ -47,3 +53,104 @@ impl<I> ContractSync<I> {
         }
     }
 }
+
+/// Tool for handling the logic of what the next block range that should be
+/// queried is and also handing rate limiting. Rate limiting is automatically
+/// performed by `next_range`.
+pub struct ContractSyncHelper<I> {
```
[the remark this answers is not in the document]
Comment (mattiecnvr) [reply rust/abacus-base/src/contract_sync/mod.rs:60]: I like where this is going, how about `SyncBlockRangeCursor`, I think it is a little better than manager.

File: rust/abacus-base/src/contract_sync/mod.rs [hunk 4]
```diff
@@ -47,3 +53,104 @@ impl<I> ContractSync<I> {
...
+    async fn rate_limit(&mut self) -> Result<()> {
+        if self.from + self.chunk_size < self.tip {
+            // If doing the full chunk wouldn't exceed the already known tip,
+            // we don't necessarily need to fetch the new tip. Sleep a tiny bit
+            // so that we can catch up to the tip relatively quickly.
+            sleep(Duration::from_secs(1)).await;
+            Ok(())
+        } else {
+            // We are close to the tip.
+            if (Instant::now() - self.last_tip_update) < Duration::from_secs(30) {
```
[the remark this answers is not in the document]
Comment (mattiecnvr) [reply rust/abacus-base/src/contract_sync/mod.rs:130]: Ah, yeah, that would be smart.

File: rust/abacus-base/src/contract_sync/mod.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (tkporter) [reply rust/abacus-base/src/contract_sync/mod.rs]: nice, yeah I agree that's better

File: rust/abacus-base/src/contract_sync/outbox.rs [hunk 5]
```diff
@@ -79,43 +84,25 @@ where
...
-                    continue;
-                }
-
-                // Index the chunk_size, capping at the tip.
-                let to = min(tip, from + chunk_size);
-
-                // Still search the full-size chunk size to possibly catch events that nodes have dropped "close to the tip"
-                let full_chunk_from = to.checked_sub(chunk_size).unwrap_or_default();
+                let start_block = cursor.current_position();
+                let Ok((from, to)) = cursor.next_range().await else { continue };
```
Comment (tkporter) [inline rust/abacus-base/src/contract_sync/outbox.rs:96]: should we log if there's an error? I think we'll get some logs if we're using QuorumProvider but because that probably shouldn't be assumed, I think logging here & in the other places we get errors from a `next_range` call would be helpful for potential debugging

File: rust/abacus-base/src/contract_sync/mod.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (tkporter) [reply rust/abacus-base/src/contract_sync/mod.rs:150]: Ok, happy to keep it with the sleep

File: rust/abacus-base/src/contract_sync/interchain_gas.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (tkporter) [reply rust/abacus-base/src/contract_sync/interchain_gas.rs]: sorry I don't think I follow, what are you suggesting we use `start_block` for?

**Comment by mattiecnvr** [comment]
Okay, I was digging through to figure out what exactly the test was failing on... Looks like it is this test sequence:
https://github.com/hyperlane-xyz/hyperlane-monorepo/blob/3d44b1919c0ec00ba333cf69b96a105d1b33f539/rust/abacus-base/src/contract_sync/outbox.rs#L264

Thinking on a good way to fix this test since ideally we would keep it. One thought I have is to just create a mock cursor.

File: rust/abacus-base/src/agent.rs [hunk 6]
```diff
@@ -132,8 +132,6 @@ pub async fn agent_main<A: BaseAgent>() -> Result<()> {
     crate::oneline_eyre::install()?;
     #[cfg(all(feature = "color_eyre", not(feature = "oneline-errors")))]
     color_eyre::install()?;
-    #[cfg(not(any(feature = "color-eyre", feature = "oneline-eyre")))]
```
Comment (tkporter) [inline rust/abacus-base/src/agent.rs:135]: was this intentionally removed?

File: rust/abacus-base/src/contract_sync/cursor.rs [hunk 7]
```diff
@@ -0,0 +1,92 @@
+use std::time::{Duration, Instant};
+
+use async_trait::async_trait;
+use eyre::Result;
+use tokio::time::sleep;
+
+use abacus_core::{Indexer, SyncBlockRangeCursor};
+
+/// Tool for handling the logic of what the next block range that should be
+/// queried is and also handing rate limiting. Rate limiting is automatically
```
Comment (tkporter) [inline rust/abacus-base/src/contract_sync/cursor.rs:10]: nit: handing => handling

File: rust/abacus-base/src/contract_sync/outbox.rs [hunk 8]
```diff
@@ -260,160 +307,100 @@ mod test {
...
+                expect_fetches_range!(141, 160, &[]);
 
                 // Stay at the same tip, so no other fetch_sorted_messages calls are made
-                mock_indexer
-                    .expect__get_finalized_block_number()
-                    .returning(|| Ok(180));
+                mock_cursor.expect__current_position().returning(|| 161);
+                mock_cursor.expect__next_range().returning(|| {
+                    Box::pin(async move {
+                        sleep(Duration::from_secs(100)).await;
```
Comment (tkporter) [inline rust/abacus-base/src/contract_sync/outbox.rs:400]: why sleep 100 secs? does this mean that tests take 100 seconds longer now

File: rust/abacus-base/src/contract_sync/outbox.rs [hunk 9]
```diff
@@ -260,160 +307,100 @@ mod test {
             let latest_valid_message_range_start_block = 100;
 
             let mut mock_indexer = MockAbacusIndexer::new();
+            let mut mock_cursor = MockSyncBlockRangeCursor::new();
             {
                 let mut seq = Sequence::new();
 
+                // Some local macros to reduce code-duplication.
+                macro_rules! expect_current_position {
```
Comment (tkporter) [inline rust/abacus-base/src/contract_sync/outbox.rs:315]: nice idea putting these into macros

File: rust/abacus-base/src/agent.rs (hunk 6 above)
Comment (mattiecnvr) [reply rust/abacus-base/src/agent.rs:135]: Yes, sorry, meant to comment on that but apparently I forgot to submit my review. This was removed because I found out it was wrong when running in debug mode. The way it is after this change is correct.

File: rust/abacus-base/src/contract_sync/outbox.rs (hunk 8 above)
Comment (mattiecnvr) [reply rust/abacus-base/src/contract_sync/outbox.rs:400]: No, actually, the tests now take only 20ms. This sleep is because it should be longer than the timeout on the tests since we don't really want to yield it at all. Adding a comment to explain this.

File: rust/abacus-base/src/contract_sync/outbox.rs (hunk 9 above)
Comment (mattiecnvr) [reply rust/abacus-base/src/contract_sync/outbox.rs:315]: Yeah, I was getting tired of both how verbose the code was getting and also how unreadable it was.
